/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brknda;

/**
 *
 * @author Mostafa Moayed
 */
public class FrmInvoice extends javax.swing.JFrame {

    /**
     * Creates new form FrmInvoice
     */
    public FrmInvoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblBrknda = new javax.swing.JLabel();
        lblView = new javax.swing.JLabel();
        pnlNavigation = new javax.swing.JPanel();
        btnInventory = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnNewOrder = new javax.swing.JButton();
        btnInvoices = new javax.swing.JButton();
        pnlInvoiceDetails = new javax.swing.JPanel();
        lblBRKNDA = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblCustomerNameAndPhone = new javax.swing.JLabel();
        lblInvoiceNO = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblCashier = new javax.swing.JLabel();
        lblInvoiceNONum = new javax.swing.JLabel();
        lblDateDay = new javax.swing.JLabel();
        lblCashierName = new javax.swing.JLabel();
        pnlInvoiceItems = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducts1 = new javax.swing.JTable();
        pnlFinancialSummary = new javax.swing.JPanel();
        lblNotes = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        lblSubTotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalJOD = new javax.swing.JLabel();
        tlblTaxJOD = new javax.swing.JLabel();
        lblSubTotalJOD = new javax.swing.JLabel();
        lblThanks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BRKNDA - Generated Invoice");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(0, 0, 153));

        lblBrknda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBrknda.setForeground(new java.awt.Color(255, 255, 255));
        lblBrknda.setText("BRKNDA - Generated Invoice");

        lblView.setForeground(new java.awt.Color(255, 255, 255));
        lblView.setText("View and print the generated customer invoice");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrknda, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addComponent(lblView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBrknda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblView)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlNavigation.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigation"));

        btnInventory.setText("Inventory");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });

        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnNewOrder.setText("New Order");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnInvoices.setBackground(new java.awt.Color(204, 255, 255));
        btnInvoices.setText("Invoices");

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnInvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigationLayout.createSequentialGroup()
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInvoices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlInvoiceDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoice Details"));

        lblBRKNDA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBRKNDA.setForeground(new java.awt.Color(0, 0, 153));
        lblBRKNDA.setText("BRKNDA");

        lblHome.setForeground(new java.awt.Color(102, 102, 102));
        lblHome.setText("Home & Kitchen Electronics");

        lblLocation.setForeground(new java.awt.Color(102, 102, 102));
        lblLocation.setText("Amman, Jordan");

        lblCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustomer.setText("Customer:");

        lblCustomerNameAndPhone.setText("Mostafa Moayed | 0770143388");

        lblInvoiceNO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInvoiceNO.setText("Invoice No:");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setText("Date:");

        lblCashier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCashier.setText("Cashier:");

        lblInvoiceNONum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInvoiceNONum.setForeground(new java.awt.Color(0, 0, 153));
        lblInvoiceNONum.setText("#INV-00992");

        lblDateDay.setText("23 May 2026");

        lblCashierName.setText("Mostafa Moayed");

        javax.swing.GroupLayout pnlInvoiceDetailsLayout = new javax.swing.GroupLayout(pnlInvoiceDetails);
        pnlInvoiceDetails.setLayout(pnlInvoiceDetailsLayout);
        pnlInvoiceDetailsLayout.setHorizontalGroup(
            pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceDetailsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBRKNDA)
                    .addGroup(pnlInvoiceDetailsLayout.createSequentialGroup()
                        .addComponent(lblCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCustomerNameAndPhone))
                    .addComponent(lblHome)
                    .addComponent(lblLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInvoiceNO)
                    .addComponent(lblDate)
                    .addComponent(lblCashier))
                .addGap(18, 18, 18)
                .addGroup(pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCashierName)
                    .addComponent(lblDateDay)
                    .addComponent(lblInvoiceNONum))
                .addGap(24, 24, 24))
        );
        pnlInvoiceDetailsLayout.setVerticalGroup(
            pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvoiceDetailsLayout.createSequentialGroup()
                        .addComponent(lblBRKNDA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLocation)
                        .addGap(18, 18, 18)
                        .addGroup(pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomer)
                            .addComponent(lblCustomerNameAndPhone)))
                    .addGroup(pnlInvoiceDetailsLayout.createSequentialGroup()
                        .addGroup(pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInvoiceNO)
                            .addComponent(lblInvoiceNONum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate)
                            .addComponent(lblDateDay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInvoiceDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCashier)
                            .addComponent(lblCashierName))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlInvoiceItems.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoice Items"));

        tblProducts1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"محضرة طعام 11-1", "1", "120", "1"}
            },
            new String [] {
                "Description", "Quantity", "Unit Price (JOD)", "Total (JOD)"
            }
        ));
        jScrollPane2.setViewportView(tblProducts1);

        javax.swing.GroupLayout pnlInvoiceItemsLayout = new javax.swing.GroupLayout(pnlInvoiceItems);
        pnlInvoiceItems.setLayout(pnlInvoiceItemsLayout);
        pnlInvoiceItemsLayout.setHorizontalGroup(
            pnlInvoiceItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
            .addGroup(pnlInvoiceItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInvoiceItemsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlInvoiceItemsLayout.setVerticalGroup(
            pnlInvoiceItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlInvoiceItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInvoiceItemsLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(107, 107, 107)))
        );

        pnlFinancialSummary.setBorder(javax.swing.BorderFactory.createTitledBorder("Financial Summary"));

        lblNotes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNotes.setText("Notes:");

        txtNotes.setText("Thank you for your purchase. Please retain this invoice for warranty purposes.");

        lblSubTotal.setText("SubTotal:");

        lblTax.setText("Tax (16%):");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("Grand Total:");

        lblTotalJOD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalJOD.setForeground(new java.awt.Color(0, 0, 153));
        lblTotalJOD.setText("139.20 JOD");

        tlblTaxJOD.setText("19.20 JOD");

        lblSubTotalJOD.setText("120 JOD");

        javax.swing.GroupLayout pnlFinancialSummaryLayout = new javax.swing.GroupLayout(pnlFinancialSummary);
        pnlFinancialSummary.setLayout(pnlFinancialSummaryLayout);
        pnlFinancialSummaryLayout.setHorizontalGroup(
            pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinancialSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFinancialSummaryLayout.createSequentialGroup()
                        .addComponent(lblNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNotes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinancialSummaryLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFinancialSummaryLayout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tlblTaxJOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubTotalJOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalJOD, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnlFinancialSummaryLayout.setVerticalGroup(
            pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinancialSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotes)
                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal)
                    .addComponent(lblSubTotalJOD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTax)
                    .addComponent(tlblTaxJOD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFinancialSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalJOD))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lblThanks.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblThanks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanks.setText("Thank you for shopping with BRKNDA!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlFinancialSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNavigation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInvoiceDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInvoiceItems, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblThanks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInvoiceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInvoiceItems, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFinancialSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThanks)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        new FrmInventory().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
       new FrmAddProduct().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
       new FrmNewOrder().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnNewOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnInvoices;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBRKNDA;
    private javax.swing.JLabel lblBrknda;
    private javax.swing.JLabel lblCashier;
    private javax.swing.JLabel lblCashierName;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblCustomerNameAndPhone;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateDay;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblInvoiceNO;
    private javax.swing.JLabel lblInvoiceNONum;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblSubTotalJOD;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblThanks;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalJOD;
    private javax.swing.JLabel lblView;
    private javax.swing.JPanel pnlFinancialSummary;
    private javax.swing.JPanel pnlInvoiceDetails;
    private javax.swing.JPanel pnlInvoiceItems;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JTable tblProducts1;
    private javax.swing.JLabel tlblTaxJOD;
    private javax.swing.JTextField txtNotes;
    // End of variables declaration//GEN-END:variables
}
