/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brknda;

/**
 *
 * @author Mostafa Moayed
 */
public class FrmNewOrder extends javax.swing.JFrame {

    /**
     * Creates new form FrmNewOrder
     */
    public FrmNewOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblBrknda = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        pnlNavigation4 = new javax.swing.JPanel();
        btnInventory4 = new javax.swing.JButton();
        btnAddProduct4 = new javax.swing.JButton();
        btnNewOrder4 = new javax.swing.JButton();
        btnInvoices4 = new javax.swing.JButton();
        pnlCustomerInformation = new javax.swing.JPanel();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblCustomerPhone = new javax.swing.JLabel();
        txtCustomerPhone = new javax.swing.JTextField();
        lblOrderNumber = new javax.swing.JLabel();
        txtORD = new javax.swing.JLabel();
        pnlAvailableProducts = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        pnlCurrentOrderItems = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducts1 = new javax.swing.JTable();
        pnlOrderSummary = new javax.swing.JPanel();
        lblSubTotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        tlblTaxJOD = new javax.swing.JLabel();
        lblSubTotalJOD = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalJOD = new javax.swing.JLabel();
        btnCompleteCheckout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BRKNDA - Process New Order");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(0, 0, 153));

        lblBrknda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBrknda.setForeground(new java.awt.Color(255, 255, 255));
        lblBrknda.setText("BRKNDA - Process New Order");

        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("Add products to the cart and complete the customer order");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrknda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBrknda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdd)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlNavigation4.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigation"));

        btnInventory4.setText("Inventory");
        btnInventory4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventory4ActionPerformed(evt);
            }
        });

        btnAddProduct4.setText("Add Product");
        btnAddProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProduct4ActionPerformed(evt);
            }
        });

        btnNewOrder4.setBackground(new java.awt.Color(204, 255, 255));
        btnNewOrder4.setText("New Order");

        btnInvoices4.setText("Invoices");
        btnInvoices4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoices4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavigation4Layout = new javax.swing.GroupLayout(pnlNavigation4);
        pnlNavigation4.setLayout(pnlNavigation4Layout);
        pnlNavigation4Layout.setHorizontalGroup(
            pnlNavigation4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigation4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInventory4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAddProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnNewOrder4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnInvoices4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavigation4Layout.setVerticalGroup(
            pnlNavigation4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigation4Layout.createSequentialGroup()
                .addGroup(pnlNavigation4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInventory4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnAddProduct4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewOrder4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInvoices4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlCustomerInformation.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Information"));

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustomerName.setText("Customer Name");

        txtCustomerName.setText("Mostafa Moayed");

        lblCustomerPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustomerPhone.setText("Customer Phone");

        txtCustomerPhone.setText("0770143388");

        lblOrderNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrderNumber.setText("Order Number");

        txtORD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtORD.setForeground(new java.awt.Color(0, 0, 153));
        txtORD.setText("#ORD-992");

        javax.swing.GroupLayout pnlCustomerInformationLayout = new javax.swing.GroupLayout(pnlCustomerInformation);
        pnlCustomerInformation.setLayout(pnlCustomerInformationLayout);
        pnlCustomerInformationLayout.setHorizontalGroup(
            pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerInformationLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerName)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerInformationLayout.createSequentialGroup()
                        .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtORD))
                    .addGroup(pnlCustomerInformationLayout.createSequentialGroup()
                        .addComponent(lblCustomerPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOrderNumber)))
                .addGap(17, 17, 17))
        );
        pnlCustomerInformationLayout.setVerticalGroup(
            pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerInformationLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerInformationLayout.createSequentialGroup()
                        .addComponent(lblCustomerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCustomerInformationLayout.createSequentialGroup()
                        .addGroup(pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerPhone)
                            .addComponent(lblOrderNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCustomerInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtORD))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlAvailableProducts.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Products"));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSearch.setText("Search");

        txtSearch.setText("Search to add...");

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"محضرة طعام 11-1", "120.00", "45"},
                {"عجانة بركندة 5 لتر", "65.00", "2"},
                {"جريل ستيل جامبو برو", "85.00", "20"},
                {"خلاط ستيل 4-1", "45.00", "12"},
                {"غسالة بركندة 10 كغم", "320.00", "8"},
                {"مكواة بخارية احترافية", "55.00", "3"}
            },
            new String [] {
                "Product Name", "Price (JOD)", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        javax.swing.GroupLayout pnlAvailableProductsLayout = new javax.swing.GroupLayout(pnlAvailableProducts);
        pnlAvailableProducts.setLayout(pnlAvailableProductsLayout);
        pnlAvailableProductsLayout.setHorizontalGroup(
            pnlAvailableProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvailableProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvailableProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlAvailableProductsLayout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAvailableProductsLayout.setVerticalGroup(
            pnlAvailableProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvailableProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvailableProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlCurrentOrderItems.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Order Items"));

        tblProducts1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"محضرة طعام 11-1", "1", "120", "1"}
            },
            new String [] {
                "Item", "Qty", "Unit Price", "Total"
            }
        ));
        jScrollPane2.setViewportView(tblProducts1);

        javax.swing.GroupLayout pnlCurrentOrderItemsLayout = new javax.swing.GroupLayout(pnlCurrentOrderItems);
        pnlCurrentOrderItems.setLayout(pnlCurrentOrderItemsLayout);
        pnlCurrentOrderItemsLayout.setHorizontalGroup(
            pnlCurrentOrderItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlCurrentOrderItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCurrentOrderItemsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlCurrentOrderItemsLayout.setVerticalGroup(
            pnlCurrentOrderItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
            .addGroup(pnlCurrentOrderItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCurrentOrderItemsLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pnlOrderSummary.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Summary"));

        lblSubTotal.setText("SubTotal:");

        lblTax.setText("Tax (16%):");

        tlblTaxJOD.setText("19.20 JOD");

        lblSubTotalJOD.setText("120 JOD");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("Total:");

        lblTotalJOD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalJOD.setForeground(new java.awt.Color(0, 0, 153));
        lblTotalJOD.setText("139.20 JOD");

        btnCompleteCheckout.setBackground(new java.awt.Color(0, 0, 153));
        btnCompleteCheckout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCompleteCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCompleteCheckout.setText("Complete Checkout");
        btnCompleteCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOrderSummaryLayout = new javax.swing.GroupLayout(pnlOrderSummary);
        pnlOrderSummary.setLayout(pnlOrderSummaryLayout);
        pnlOrderSummaryLayout.setHorizontalGroup(
            pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCompleteCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(pnlOrderSummaryLayout.createSequentialGroup()
                        .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTax, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tlblTaxJOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubTotalJOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlOrderSummaryLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalJOD)))
                .addContainerGap())
        );
        pnlOrderSummaryLayout.setVerticalGroup(
            pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal)
                    .addComponent(lblSubTotalJOD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTax)
                    .addComponent(tlblTaxJOD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalJOD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompleteCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNavigation4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCustomerInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlAvailableProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCurrentOrderItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlOrderSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNavigation4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCustomerInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAvailableProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlCurrentOrderItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(pnlOrderSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProduct4ActionPerformed
      new FrmAddProduct().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnAddProduct4ActionPerformed

    private void btnCompleteCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteCheckoutActionPerformed
javax.swing.JOptionPane.showMessageDialog(this, "Order Completed successfully! Invoice #INV-00992 generated.");
new FrmInvoice().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnCompleteCheckoutActionPerformed

    private void btnInventory4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventory4ActionPerformed
new FrmInventory().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnInventory4ActionPerformed

    private void btnInvoices4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoices4ActionPerformed
      new FrmInvoice().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnInvoices4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNewOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct4;
    private javax.swing.JButton btnCompleteCheckout;
    private javax.swing.JButton btnInventory4;
    private javax.swing.JButton btnInvoices4;
    private javax.swing.JButton btnNewOrder4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblBrknda;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerPhone;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblSubTotalJOD;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalJOD;
    private javax.swing.JPanel pnlAvailableProducts;
    private javax.swing.JPanel pnlCurrentOrderItems;
    private javax.swing.JPanel pnlCustomerInformation;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNavigation4;
    private javax.swing.JPanel pnlOrderSummary;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTable tblProducts1;
    private javax.swing.JLabel tlblTaxJOD;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JLabel txtORD;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
